name = "Silas Origins"
author = "FrostyTacos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89ddb2e227e227ac6caaa0e2343290a4a93f4bf22aa10fd4802bd680dcbcd12d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
