name = "Silas Origins"
author = "FrostyTacos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b33860a896bf544982013559772b339a1361fc4a35ed52a9fcda03c9a2d26b12"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
