name = "Silas Origins"
author = "FrostyTacos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7044fec79bdd781c39ab26fce9d4cf94ab7e0a891cb564f9fbe3b3262a94aab8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
